timezone: Pacific/Auckland

paths:
  static: 'public'
  uploads: public/images

collections_config:
  pages:
    path: src/content/pages
    glob:
      - '**/*.md'
    url: '/[full_slug]/'
    icon: laptop_mac
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        remove_extra_inputs: false
    create:
      path: '[relative_base_path]/{title|slugify}.md'
  data:
    path: data
    disable_add: true
    disable_add_folder: true
    _inputs:
      icons:
        comment: Add an icon from the list of [Font Awesome icons](https://fontawesome.com/search?o=r&m=free). Then add it to the ```src/components/utility/icon.jsx``` file, following the existing pattern.

data_config:
  icons:
    path: data/icons.json
  colors:
    path: data/colors.json

file_config:
  - glob: data/colors.json
    _structures:
      color:
        values:
          - value:
              name:
              value:
            preview:
              icon: palette
    _inputs:
      $:
        type: array
        label: Colors
        comment: Set the colors available in the color selectors throughout the site.
        options:
          structures: _structures.color
      value:
        type: color
      name:
        type: text
        comment: What is seen in the color selector dropdown.

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data

_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true

_inputs:
  text_content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      link: true
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  image_path:
    type: image
    comment: The path to the source file of the image to be optimized.
    options:
      paths:
        static: ''
        uploads: src/assets/images
  alt_text:
    label: Image Alt Text
    type: textarea
    hidden: '!image_path'
  width:
    type: number
  height:
    type: number
  background_color:
    hidden: 'border_only'
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  background_color_mobile:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  text_color_mobile:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  hover_text_color_mobile:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  hover_text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  icon:
    type: select
    options:
      values: data.icons
  button_icon:
    type: select
    options:
      values: data.icons
  button_link:
    type: url
  hover_brightness:
    type: range
    options:
      min: 0
      max: 1.5
      step: 0.05
  seo:
    type: object
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  layout:
    hidden: true
  social:
    type: object
    options:
      preview:
        icon: link
  links[*]:
    type: object
    options:
      preview:
        icon: link
        text:
          - key: text
          - 'Link'
        subtext:
          - key: link
          - 'Add a social link'
  social_icon:
    type: select
    options:
      values: data.icons
  social[*]:
    type: object
    options:
      preview:
        icon: query_stats
  logo:
    type: image
    options:
      paths:
        static: ''
        uploads: src/assets/images
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    type: select
    options:
      values:
        - website
        - article
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  twitter_site:
    type: url
  no_index:
    type: checkbox
    comment:
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
  background_filters:
    type: object
    comment: Set brightness and blur filters over the background video to make the text content more legible.
    options:
      preview:
        icon: exposure
  brightness:
    type: range
    options:
      min: 0
      max: 100
      step: 1
  blur:
    type: range
    options:
      min: 0
      max: 10
      step: 0.25
  background_gradient:
    type: object
    comment: A color gradient overlaying the background image. Select color as transparent to remove the color gradient.
    options:
      preview:
        icon: gradient
  gradient_enabled:
    type: switch
    comment: Enable a color gradient over the background image. Useful for adding a light to dark gradient.
  gradient_transparency:
    type: range
    comment: Control how far transparent the gradient filter is over the background image. Set this low to have a more pronounced color gradient over the image.
    options:
      min: 0
      max: 100
      step: 1
  gradient_direction:
    type: select
    comment: The direction of the color gradient.
    options:
      values:
        - top
        - bottom