# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero - Background Image
  description: 
  icon: 'cottage'
  tags:
    - Text
    - Background image

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: 
    text_color: '#a0a2ff'
  background_image:
    image_path: 
    alt_text: 
  background_filters:
    brightness:
    blur:
    background_gradient:
      gradient_enabled: true
      gradient_direction: bottom
      gradient_color: '#000000'
      gradient_transparency: 50
      gradient_start: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - key: heading_gradient_color
          - 'Update heading gradient color and text content.'
  background_image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
    