# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Outline color
  icon: 'cottage'
  tags:
    - Image
    - Animation
    - Text
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Astro Bookshop Starter
    text_color: '#a0a2ff'
  image:
    image_path: /src/assets/images/featured-image-5.jpg
    alt_text: An image
  background_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - key: heading_gradient_color
          - 'Update heading gradient color and text content.'
  image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
