# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Tabbed text
  description: Tabs of plain text
  icon: 'tab'
  tags:
    - Tabs

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#ffffff'
  heading:
    heading_text: 
    text_color: '#393939'
  tab_headings:
    tab_headings_text_color: '#393939'
    tab_subheadings_text_content: Read more
    tab_subheadings_text_color: '#272D2D80'
  tabs: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  tabs:
    type: array
    options:
      structures: _structures.tab_contents
  tab_headings_text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  tab_subheadings_text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - key: heading_gradient_color
          - 'Update heading gradient color and text content.'

_structures:
  tab_contents:
    values:
      - value:
          tab_heading: 
          text_content:
          text_color: '#272D2D'
          background_color: '#ffffff'