# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Text - Background image
  description: 
  icon: 'image'
  tags:
    - Background Image
    - Text
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  mobile_styles:
    background_color: '#58825F'
    text_color: '#F9EEDE'
  desktop_tab_styles:
    heading_background_color: '#F9EEDE'
    heading_text_color: '#58825F'
    heading_active_background_color: '#58825F'
    heading_active_text_color: '#F9EEDE'
    text_background_color: '#F9EEDE'
    text_color: '#272D2D'
  tabs:
    - image:
        image_path: 
        alt_text: 
      text:
        text_heading:
        text_content: 
        text_color: '#a0a2ff'
    
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    options:
      preview:
        icon: 'description'
        text:
          - key: text_content
          - Text
        subtext:
          - key: text_color
          - 'Update heading gradient color and text content.'
  image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
    