# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Slider
  description: 
  icon: 'swipe'
  tags:
    - Text slider
    - Background image

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Testimonials
    text_color: '#F9EEDE'
  slides:
    - slide_heading: Caylin
      text_content: >-
        ‘Becca always made me feel so welcome during class that once we moved to Japan I decided to reach out for private online lessons. I thought maybe it would be hard to have someone teach a physical practice via a screen but it’s just like being in person. We meet online once or twice a week regardless of if we are travelling or at home and she always creates a class that is unique, challenging and tailored to how I’m feeling.’
      text_color: '#F9EEDE'
    - slide_heading: Isabelle
      text_content: >-
        ‘Becca’s teaching style is exceptional - she combines clear guidance, encouragement, and a deep understanding of the body, making every participant feel confident and empowered to explore their limits safely. Also it was just a lot of fun. We all laughed along the way, without taking it too seriously.’  
      text_color: '#F9EEDE'
  background_image:
    image_path: /src/assets/images/jade-stephens-unsplash.jpeg
    alt_text: Jade Stephens Unsplash - Clouds over a sea
  background_filters:
    brightness: 80
    blur: 0
    background_gradient:
      gradient_enabled: false
      gradient_direction: bottom
      gradient_color: '#000000'
      gradient_transparency: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: